name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: uv lock --check
      - run: uv sync --locked --dev
      - run: uv run ruff check .
      - run: uv run ruff format --check .
